docker-compose-yaml: docker-compose.yml

project: glyn-drupal-base

tasks:
  pre-rollout:

  post-rollout:
    - run:
        name: drush updb
        # This will only run if the database exists.
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush -y updb; fi
        service: cli
        shell: bash
    - run:
        name: drush cr
        # This will only run if the database exists.
        command: |
          if [[ $(drush status --field=Database) == "Connected" ]]; then drush -y cr; fi
        service: cli
        shell: bash

environments:
  main:
    cronjobs:
      - name: drush hourly cron
        schedule: "M * * * *"
        command: drush cron
        service: cli
    routes:
      - nginx:
        - drupal-base.scratchydog.net
